### PR TITLE
Update: added connected message

### PR DESCRIPTION
**Pull request by vytautas-pranskunas-**
#### Fixes / Enhancements

Added message when websocket is connected

#### Docs
Added message when websocket is connected

## Upteda by @vincenzopalazzo 

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1308

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
please change the commit header to `feat(graphql): print the connection status with ws`

**Comment by vincenzopalazzo** [comment]
also the CI is complaing
```
8s
Run make ci_fmt_client
dart pub global run melos run client_analyze --no-select
melos run client_analyze
  └> melos exec -c [1](https://github.com/zino-hofmann/graphql-flutter/actions/runs/4425459030/jobs/7760880769#step:5:1) -- "dart format --set-exit-if-changed . && dart analyze . --fatal-infos"
     └> RUNNING

$ melos exec
  └> dart format --set-exit-if-changed . && dart analyze . --fatal-infos
     └> RUNNING (in 2 packages)

--------------------------------------------------------------------------------
example:
Formatted 3 files (0 changed) in 0.2[7](https://github.com/zino-hofmann/graphql-flutter/actions/runs/4425459030/jobs/7760880769#step:5:8) seconds.
Analyzing ....
No issues found!
example: SUCCESS
--------------------------------------------------------------------------------
graphql:
Formatted lib/src/links/websocket_link/websocket_client.dart
Formatted 54 files (1 changed) in 0.79 seconds.
--------------------------------------------------------------------------------

$ melos exec
  └> dart format --set-exit-if-changed . && dart analyze . --fatal-infos
     └> FAILED (in 1 packages)
        └> graphql (with exit code 1)

melos run client_analyze
  └> melos exec -c 1 -- "dart format --set-exit-if-changed . && dart analyze . --fatal-infos"
     └> FAILED
ScriptException: The script client_analyze failed to execute
make: *** [Makefile:[32](https://github.com/zino-hofmann/graphql-flutter/actions/runs/4425459030/jobs/7760880769#step:5:33): ci_fmt_client] Error 1
```

**Comment by vytautas-pranskunas-** [comment]
Changed

**Comment by vincenzopalazzo** [comment]
Need commit need to be removed https://github.com/zino-hofmann/graphql-flutter/pull/1309/commits/7757b8b17cfaf4cb83e856cde5238d841cf8d406 

This required to squash your commit with the previous one

**Review by vincenzopalazzo — APPROVED** [review]

**Comment by vytautas-pranskunas-** [comment]
when it will be released?

**Pull request merged**
