### PR TITLE
Fix wrong default policy merging in `useWatchQuery/Mutation`.

### PR DESCRIPTION
**Pull request by dehypnosis**
Hi, thanks to great work.
Current `useWatchQuery` refers to `defaultPolicies.query` rather given `defaultPolicies.watchQuery`.
Also `useWatchMutation` refers to `defaultPolicies.mutate`.

If it is not intentional... please check this PR.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
I this required some more love for the graphql_flutter test?

**Comment by dehypnosis** [comment]
@vincenzopalazzo  I was so busy doing my own business. And wanna express my gratitude for this awesome package again. Fixed a related test case.

**Review by vincenzopalazzo — COMMENTED** [review]
LGTM thanks, lest's see what @budde377 said too on this change too, he is the boss of the hooks 😄 

In addition, can you add the commit message in this pattern `fix(graphql): Fix wrong default policy merging in useWatchQuery/Mutation` we generate the changelog from this message!

**Review by budde377 — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
