### PR TITLE
Fixed websocket reconnection when network connection is lost

### PR DESCRIPTION
**Pull request by psrcek**
Fixes https://github.com/zino-app/graphql-flutter/issues/856

### CODE REVIEW

**Comment by psrcek** [comment]
@micimize why did you close this? What's wrong with the changes? this fixes a major bug that is a dealbreaker to many.

**Comment by Bligoubloups** [comment]
I agree with @psrcek.
It fixes a major bug.

**Comment by micimize** [comment]
It was closed by me deleting `nullsafety`. Reopened and changed the base

**Review by micimize — CHANGES_REQUESTED** [review]
So, I think actually the best thing to do here would be to open a PR against `web_socket_channel`  attempting to fix the issue there. That way we can solve the problem at the root and not have to do workarounds ourselves.

Also, I think this workaround can be done directly in the `connect` config argument. I don't like having a broken default, but it makes waiting for/following up with the dependency issue more palatable.

I would still merge a workaround that handles the platform-conditional imports though

**Comment by vytautas-pranskunas-** [comment]
Can we merge it somehow?
@psrcek how you manage to solve it? Are you living with local copy or?

**Comment by psrcek** [comment]
> how you manage to solve it?

@vytautas-pranskunas- I'm currently just using my fork (the one this pr is requesting to merge) because I don't need web support.

**Comment by vytautas-pranskunas-** [comment]
I also do not need web support so started to use this code.. However it should be fixed.
Also i wonder has this project active maintainer because it looks like @micimize is out.

**Comment by Bligoubloups** [comment]
I need this fix ...

**Comment by Bligoubloups** [comment]
Didn't know how to make the changes on this pr :/
So I created a new one #963

**Comment by vytautas-pranskunas-** [comment]
The problem is that nobody can approve you PR :( this project has no active maintainer and as far as i know nobody took over... So basicaly is dead.. it is very pity because we are now without GQL library in flutter.

**Comment by Bligoubloups** [comment]
Micimize said "I would still merge a workaround that handles the platform-conditional imports though".
And Im sure he will.

**Comment by vytautas-pranskunas-** [comment]
@micimize would you?

**Comment by vytautas-pranskunas-** [comment]
@vincenzopalazzo Greetings. Have just read that you became a new maintainer :) Cool. his issue is very important because of this websocket keeps disconnecting. Because of this I have fully duplicated websocket code in my project. Many sufers from this. This would be great place to start :) let me know :)

**Comment by vincenzopalazzo** [comment]
Hi @vytautas-pranskunas- 

Thanks, I will take a look as soon a possible, and when we have again all up and running in the repository.

**Comment by kateile** [comment]
@vytautas-pranskunas- hi, any progress on this?

**Comment by vincenzopalazzo** [comment]
@kateile 

Under Review, for this week https://github.com/zino-hofmann/graphql-flutter/pull/963#issuecomment-997341746

Sorry for delay here

**Comment by vincenzopalazzo** [comment]
Closing in favor of https://github.com/zino-hofmann/graphql-flutter/pull/963

**Pull request closed without merging**
