### PR TITLE
Fix duplicate pollers firing

### PR DESCRIPTION
**Pull request by apackin**
### Fixed Issue
Calling stopPolling, followed quickly by startPolling, does not remove the first poller and results in duplicate pollers.

### Reproducing issue
 Create an observable query and call 
 ```
  void startDupPolling(Duration duration) {
    _observableQuery.startPolling(duration);
    _observableQuery.startPolling(duration);  // Internally calls `stopPolling` if poller is running
 }
```
Or
 ```
  void startDupPolling(Duration duration) {
    _observableQuery.startPolling(duration);
    _observableQuery.stopPolling();
    _observableQuery.startPolling(duration);
 }
```
Starts two pollers instead of one.

### Explanation
```
  /// Removes the [ObservableQuery] from one of the registered queries.
  /// The fetchQueriesOnInterval will then take care of not firing it anymore.
  void stopPollingQuery(String queryId) {
    registeredQueries.remove(queryId);
  }
```

stopPolling is expecting fetchQueriesOnInterval to remove the stopped poll. This only happens if `registeredQueries[queryId] == null` is true when `fetchQueriesOnInterval` is run. Calling `startPolling` again quickly, adds a new entry to `registeredQueries[queryId]` before fetchQueriesOnInterval, thus leading to duplicate entries in `intervalQueries`. Since `registeredQueries[queryId]` is true, all entries for the queryId in `intervalQueries` get fired, instead of the stopped ones being removed.

### The Fix
By making `intervalQueries` store a set, we prevent duplicate entries from being added for the same duration. Thus the value of `registeredQueries[queryId]` applies to the only value for that queryId in the set.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
this need a commit entry, to learn more about it you can take a look to https://github.com/zino-hofmann/graphql-flutter/blob/main/docs/dev/MAINTAINERS.md

**Comment by apackin** [comment]
> this need a commit entry, to learn more about it you can take a look to https://github.com/zino-hofmann/graphql-flutter/blob/main/docs/dev/MAINTAINERS.md

Thanks for the reply! I updated the first commit according to those docs. Let me know if that works. I also added test coverage for polling. Is there a command to rerun codecov bot?

**Review by budde377 — DISMISSED** [review]

**Comment by apackin** [comment]
Thanks for reviewing this @budde377! Is there a command to rerun the build tests?

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
nit: your PR is to the beta branch, and not in the main.

This is the cause of the following error in the CI

```
Analyzing graphql_flutter...                                    

warning • The '!' will have no effect because the receiver can't be null • lib/src/widgets/cache_provider.dart:27:28 • unnecessary_non_null_assertion
warning • The '!' will have no effect because the receiver can't be null • lib/src/widgets/cache_provider.dart:45:28 • unnecessary_non_null_assertion
```

**Comment by vincenzopalazzo** [comment]
Ok! 

A couple of comment:

1. You should use the rebase intend of the merge to keep the history clean https://www.atlassian.com/git/tutorials/merging-vs-rebasing
2. You should comment what this commit means in the header https://github.com/zino-hofmann/graphql-flutter/pull/1219/commits/c87556c78d6c3c61e002c661be8f17624d9c7e6f

The solution that I suggest to you is to cherry-pick you commit in a new clean branch, I think you build on beta, that it is history now!

**Comment by apackin** [comment]
Got it. I'll do that. Thanks for the help!

**Comment by apackin** [comment]
PRed from clean branch as recommended https://github.com/zino-hofmann/graphql-flutter/pull/1240

**Pull request closed without merging**
