### PR TITLE
fix(graphql): add query timeout argument when create client.

### PR DESCRIPTION
**Pull request by ykuc7**
#### Enhancements
- Add query timeout argument when create client.
- Related #1446

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
Thanks!

**Comment by souravdasslg** [comment]
I needed this functionality, what is the release plan for this ? 🙏

**Comment by ykuc7** [comment]
@vincenzopalazzo 
I resolved conflicts. Cloud you approve and merge PR?

**Comment by vincenzopalazzo** [comment]
Thanks @ykuc7 but could you remove the merge commit 1b52d198e98be4c183b626caaba91a3622b8a100 and just rebase on main

**Comment by ykuc7** [comment]
@vincenzopalazzo 
Rebased and force pushed.

**Comment by uri-ravzin** [comment]
any chance we could have the argument as optional?

e.g. we prefer to let server handle the timeout and let the client library remain as it was before this change :)

**Comment by uri-ravzin** [comment]
> @uri-ravzin PR are welcome if you add a good justification on why you need it optional

We like to let the server handle the timeout. (as it was in older versions here as well)

short timeouts can lead to repeated requests, unexpected results, and actually increased load on the server, by users who just want to have their requests to complete.

Specifically in our product, we like the upgrades and are fast adopters to all beta releases, but currently seem to be stuck on 5.2.0-beta.7 due to this new introduced mandatory parameter.

**Pull request merged**
