### PR TITLE
fix(graphql_flutter): upgrade dependency `connectivity_plus`

### PR DESCRIPTION
**Pull request by johnmartel**
Upgrades dependency [connectivity_plus](https://pub.dev/packages/connectivity_plus)  to its next major version (^6.0.1). 

This will be helpful for projects that depend on both `connectivity_plus` and `graphql_flutter` to keep their dependencies up-to-date. Without this upgrade here, downstream projects could have a dependency conflict between `connectivity_plus` `^5.0.0` and `^6.0.1`.

#### Fixes / Enhancements

- Updated dependency [connectivity_plus](https://pub.dev/packages/connectivity_plus)

### CODE REVIEW

**Comment by johnmartel** [comment]
See #1423 and #1424

**Comment by johnmartel** [comment]
@vincenzopalazzo I'm sorry, somehow the line length isn't configured correctly. Let me know if this is an issue and what's your preferred.

**Comment by JosueHernandezR** [comment]
Still no updates? :c

**Review by vincenzopalazzo — APPROVED** [review]
LGTM

**Pull request merged**
