### PR TITLE
update gql_exec, gql_link, gql_http_link

### PR DESCRIPTION
**Pull request by toonvanstrijpwavy**
Working on an update to `graphql_codegen` this makes use of `gql_code_builder`. Which makes use of `gql_exec: ^0.4.0`.

#### Fixes / Enhancements

- Updated gql_exec
- Updated gql_link
- Updated gql_http_link

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
update just the pub deb looks like not enoght!

**Comment by toonvanstrijpwavy** [comment]
@vincenzopalazzo the tests are failing because I cannot change this line since it's making use of the published beta package: [line](https://github.com/zino-hofmann/graphql-flutter/pull/1051/files#diff-8f6293e6338d3f5bd980e18143fe2569fbf49d654b49dc5b2c8b7e1e592b9d1aL6)

**Comment by vincenzopalazzo** [comment]
it is not the problem of dependencies, or better it is not ONLY, please take a look at this https://github.com/zino-hofmann/graphql-flutter/runs/5274956012?check_suite_focus=true#step:4:256

There is one reason that we stay with the fixed version of gql_exec: 0.3.0, we are not only lazy

**Comment by toonvanstrijpwavy** [comment]
@vincenzopalazzo could you let me know if this needs any more work?

**Comment by vincenzopalazzo** [comment]
>@vincenzopalazzo could you let me know if this needs any more work?

we need to fix the CI if you rebase now you have melos to play with, if you want I can do it, but I have other things in my TODO list before fixing this PR

**Comment by toonvanstrijpwavy** [comment]
@vincenzopalazzo I updated it but somehow melos doesn't override the packages properly. Because of that `graphql-flutter` still uses the specified dependency in `pubspec.yaml`. We could fix this by adding a `dependency_overrides` but that's not the way to go I think.

**Comment by vincenzopalazzo** [comment]
>@vincenzopalazzo I updated it but somehow melos doesn't override the packages properly. Because of that graphql-flutter still uses the specified dependency in pubspec.yaml. We could fix this by adding a dependency_overrides but that's not the way to go I think.

Right, in the near future blob PR will be not accepted anymore, in fact, one PR like that need to be divided in two different PR one for `graphql` and one for `graphql_flutter`

>I updated it but somehow melos doesn't override the packages properly. 

Melos is an env manager, not versioning management, this means that in the CI we test the package with clean flutter action, we don't take into consideration melos, so in this case, the `dependency_overrides` is the only solution. But I'm working to improve the ci and the release process, and we will have more strict rules for each PR.

The PR that will make this PR workable is open here #1055

**Comment by toonvanstrijpwavy** [comment]
@vincenzopalazzo Alright that makes sense! Then let's wait for the other PR to get merged.

**Comment by vincenzopalazzo** [comment]
Sorry for the delay here @toonvanstrijpwavy, I merged the change, if you rebase on the last main branch we can start to work on fixing the CI error in this PR

**Review by vincenzopalazzo — APPROVED** [review]
I found this response propriety confusing, but the PR looks good to me.

Let's ping @budde377 and wait for the review, maybe he has other experience with this gql package version and has some different opinions from mine.

**Comment by toonvanstrijpwavy** [comment]
@vincenzopalazzo I'm not sure what you mean by that, If I did something wrong, or handled inappropriate please let me know? Besides that, thanks for taking a look at it! 😄

**Comment by vincenzopalazzo** [comment]
>I'm not sure what you mean by that, If I did something wrong, or handled it inappropriately please let me know? Besides that, thanks for taking a look at it! 

There is nothing wrong, but I just ask myself why in this case we need an empty map as a response. But it is not your fault, it is from the gql API

**Review by budde377 — APPROVED** [review]
Thanks for pinging @vincenzopalazzo, I stumbled upon this myself and was not sure if this is the right approach. But I don't have a better solution for cached data, so I'd say let's go. We can revisit later if something else makes more sense :) 

Thank you for your contribution @toonvanstrijpwavy!

**Pull request merged**
