### PR TITLE
fix: subscription broadcast

### PR DESCRIPTION
**Pull request by budde377**
Subscriptions aren't rebroadcasted! This PR fixes this and adds a test.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
looks like there is a import missing around
`
error • The function 'initHiveForFlutter' isn't defined • test/widgets/query_test.dart:[11](https://github.com/zino-hofmann/graphql-flutter/runs/5229431340?check_suite_focus=true#step:6:11)5:11 • undefined_function`

**Comment by budde377** [comment]
@vincenzopalazzo, removed!

**Review by vincenzopalazzo — APPROVED** [review]
Thanks for all these bug fixing

**Comment by steebchen** [comment]
Thanks, this is great to have 😁🙏

**Pull request merged**
