### PR TITLE
ci: split the release process between package

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
This PR preparing the release process to be split into two

Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1064
Fixes https://github.com/zino-hofmann/graphql-flutter/issues/1022

In addition, this will remove the circleci from the CI and make the release process more flexible, with the following rules:

- The changelog needs to be generated before the release, with the following cmd tool https://github.com/vincenzopalazzo/changelog.dart/releases/tag/v0.0.1-alpha.2 with the most recent version.
The to use the command line tool we need to run the following command after downloading it
```
export GITHUB_TOKEN="your_token"
changelog-cli -p {package_name} -v v{version_number} -g zino-hofmann/graphql-flutter -b main -m header
# create the changelog.md file, if already exist it will join the result, so it is important ran the tool inside the package directory
```
- The version needs to be bumped manually inside the pubspec.yml, this is a feature because allow us to make typo inside the release and make the github less magic when we release some package due to the auto bumping of the release
- To release a single package we need to create a release with the following tag `{package_name}-v{version_number}` if we release with the tag `v{version_number}` this release all the package, useful for a major release of the package :)

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
For a stupid error in the evaluation inside the ci I push the beta.7 https://pub.dev/packages/graphql/versions/5.0.2-beta.7 at list we can see that it works!

Sorry about that!

**Comment by budde377** [comment]
Awesome! Can you add a doc (e.g. `RELEASEING.md`) with an idiots guide to releasing a new version? 

Also, it would be pretty awesome if this could be a one-step process. E.g., add the changelog generator to dev dependencies so I don't have to download it. Add new command aliases so I don't need to write the package name, etc. 

WDYT?

**Comment by vincenzopalazzo** [comment]
>Awesome! Can you add a doc (e.g. RELEASEING.md) with an idiots guide to releasing a new version?

 Yes, it is a good idea, thanks for the suggestion!

>Also, it would be pretty awesome if this could be a one-step process. E.g., add the changelog generator to dev dependencies so I don't have to download it. Add new command aliases so I don't need to write the package name, etc.

Mh, good idea too, I need to find the way how pull out with dart pub the binary :) and I will write the script to do it.

**Comment by vincenzopalazzo** [comment]
@budde377  Updated the docs in https://github.com/zino-hofmann/graphql-flutter/pull/1088 

If you agree I will merge this and Improve it later to make small changes inside PRs, what do you think?

**Review by budde377 — APPROVED** [review]

**Pull request merged**
