### PR TITLE
Fix SocketClient to close subscription on socket close

### LINKED ISSUE #1183: Subscription stream is not closed on SocketException
Hello. I want to display connection status to the graphql server.
I created WebSocketLink with `autoReconnect: false` as following because I want to display red circle on disconnected/connecting state. I had no luck to get any control when SocketException is raised (I start the app without letting server up, or take server down after the app started)

```dart
var wsLink = WebSocketLink(args['wsEndpoint']!,
      config: const SocketClientConfig(
        autoReconnect: false,
        inactivityTimeout: null,
      ));
```
```dart
  void subscribeReadiness() {
    debugPrint('subscribeReadiness');

    var subscription = client
        .subscribe(SubscriptionOptions(
            document: gql(
      r'''subscription { isReady }''',
    )))
        .listen(
      (result) {
        debugPrint('onData:' + result.toString());

        if (result.hasException) {
          print(result.exception.toString());
          return;
        }

        if (result.isLoading || result.data == null) {
          print('awaiting result');
          return;
        }

        setState(() {
          isReady = result.data!['isReady']! as bool;
        });
      },
      onDone: () {
        debugPrint('onDone');
        setState(() {
          isReady = false;
        });
        Future.delayed(
            const Duration(seconds: 1), () => {subscribeReadiness()});
      },
      onError: (error) {
        debugPrint(error.toString());
      },
      cancelOnError: false,
    );
  }
```

**Expected behavior**
`onError`, or at least `onDone` must be called.  I've inspected `websocket_client.dart` code, but it seems not to have any code to close all streams in `onConnectionLost()`. 

**device / execution context**
macos 12.4

### PR DESCRIPTION
**Pull request by qbx2**
Closes #1183

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
we can try to have some tests for this?

**Comment by qbx2** [comment]
I’ll try

**Comment by qbx2** [comment]
I added a test for onDone(). However, I have no idea to test onError().

**Comment by vincenzopalazzo** [comment]
I'm too lazy to fix the git history and the commit message! So I just cherry picked your commit https://github.com/zino-hofmann/graphql-flutter/pull/1186

**Pull request closed without merging**
