### PR TITLE
docs: Removed extra space between sections

### PR DESCRIPTION
**Pull request by Dinokojt7**
Describe the purpose of the pull request.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]

**Comment by vincenzopalazzo** [comment]
Can you change the commit header to `docs: Removed extra space between sections` otherwise this will go inside the changelog but is doing nothing

**Comment by Dinokojt7** [comment]
Alright will do so

**Comment by Dinokojt7** [comment]
Please check and tell me if it's sorted.

**Review by Dinokojt7 — COMMENTED** [review]
docs: Removed extra space between sections

**Comment by vincenzopalazzo** [comment]
>docs: Removed extra space between sections

are you kidding me?

```
git commit --amend
```

and then put `docs: Removed extra space between sections` on the first line

**Pull request closed without merging**
